### ISSUE TITLE
[bug]:  bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'oddfar_campus.i_shop' doesn't exist

### ISSUE THREAD

**Issue by czmchen** [oddfar/campus#13]
## 版本情况

Campus版本： 1.0.11（docker hub latest版本）

## 问题描述
os:centeros7.6
mysql:5.7
安装部署方式：docker
docker安装部署，执行命令docker pull oddfar/campus-imaotai:latest
按照配置上application-prod.yml配置好mysql，redis
mysql也导入了https://github.com/oddfar/campus-imaotai/blob/master/doc/sql/campus_imaotai-1.0.5.sql
运行启动没报错，前端部署完成后系统也能正常登陆进去，但是点击i茅台模块的菜单，基本都是卡顿不动，看ssh的campus-imaotai的容器日志才发现找不到表，但是我已经导入并且里面也自动初始化了数据（系统启动后自动初始化数据，说明连接正确），库表如下
![image](https://github.com/oddfar/campus/assets/13728446/bbaf7c56-f50e-4456-ad92-e02b3cc92af1)
![image](https://github.com/oddfar/campus/assets/13728446/497ee66e-ba79-4586-879c-079479a68e6a)

错误如下：
1. 复现代码
2024-03-13 14:32:49 |INFO   |DynamicRoutingDataSource.java:243 |dynamic-datasource initial loaded [1] datasource,primary datasource named [master]
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.4.1 
Exception in thread "Thread-2" org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Table 'oddfar_campus.i_shop' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'oddfar_campus.i_shop' doesn't exist
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
        at com.sun.proxy.$Proxy115.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:152)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
        at com.sun.proxy.$Proxy120.truncateShop(Unknown Source)
        at com.oddfar.campus.business.service.impl.IShopServiceImpl.refreshShop(IShopServiceImpl.java:76)
        at com.oddfar.campus.business.service.impl.IShopServiceImpl$$FastClassBySpringCGLIB$$5cecaa53.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at com.oddfar.campus.business.service.impl.IShopServiceImpl$$EnhancerBySpringCGLIB$$f9254385.refreshShop(<generated>)
        at com.oddfar.campus.business.service.impl.IMTServiceImpl.refreshAll(IMTServiceImpl.java:509)
        at com.oddfar.campus.business.service.impl.IMTServiceImpl$1.run(IMTServiceImpl.java:72)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: Table 'oddfar_campus.i_shop' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy156.update(Unknown Source)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
        at com.sun.proxy.$Proxy155.update(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
        ... 16 more
2024-03-13 14:32:57 |INFO   |JacksonConfig.java:46 |鍒濆鍖� jackson 閰嶇疆
2024-03-13 14:32:58 |INFO   |DirectJDKLog.java:173 |Starting ProtocolHandler ["http-nio-8160"]
2024-03-13 14:32:58 |INFO   |StartupInfoLogger.java:61 |Started CampusApplication in 16.519 seconds (JVM running for 17.553)
error from daemon in stream: Error grabbing logs: invalid character 'l' after object key:value pair

2. 测试涉及到的文件

**Comment by czmchen** [comment]
![image](https://github.com/oddfar/campus/assets/13728446/bd5497ec-c4ff-4390-a3ce-1cc330783049)
